system:
  num_client: 30
  num_local_class: 2
  dataset: "CIFAR10"
  model: "AlexCifarNet"
  i_seed: 235235
  num_round: 200
  res_root: "results"
  noniid: true
  imbalance_factor: 0.6
  similarity_method: "wasserstein"
  concurrent: true
  malicious_ratio: 0
  attack_type: "zero"

client:
  fed_algo: "FedAvg"
  lr: 0.01
  batch_size: 64
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2
