system:
  num_client: 200
  num_local_class: 2
  dataset: "MNIST"
  model: "LeNet"
  i_seed: 235235
  num_round: 100
  res_root: "results"
  imbalance_factor: 0.6
  similarity_method: "wasserstein"

client:
  fed_algo: "FedAvg"
  lr: 0.01
  batch_size: 64
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2