system:
  num_client: 150
  num_local_class: 2
  dataset: "MNIST"
  model: "LeNet"
  i_seed: 235235
  num_round: 200
  res_root: "results"
  noniid: false
  imbalance_factor: 0.3
  similarity_method: "wasserstein"

client:
  fed_algo: "FedAvg"
  lr: 0.01
  batch_size: 64
  num_local_epoch: 5
  momentum: 0.9
  num_worker: 2